# Generated by Django 3.0.9 on 2020-08-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='isPublished',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='description',
            field=models.TextField(verbose_name='Söz'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='image',
            field=models.CharField(max_length=50, verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Söz Konusu'),
        ),
    ]
