# Generated by Django 3.0.9 on 2020-08-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20200816_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
    ]
